### ISSUE TITLE
可以考虑做下seo

### ISSUE THREAD

**Issue by g0fcn** [WangZhiYao/bing.339.im#1]

**Comment by g0fcn** [comment]
tag,每日一张太少了

**Comment by g0fcn** [comment]
没想到hexo这能做壁纸站

**Comment by WangZhiYao** [comment]
> 没想到hexo这能做壁纸站

这个做着好玩的，实际上这个主题有缺陷，[Archives](https://bing.339.im/archives/) 页面有无法分页，所以我也在寻找一个别的主题

**Comment by g0fcn** [comment]
hexo貌似没什么壁纸主题，可以考虑把壁纸当-文章发，顶多就是把hexo主题主页改瀑布流

**Comment by WangZhiYao** [comment]
> hexo貌似没什么壁纸主题，可以考虑把壁纸当-文章发，顶多就是把hexo主题主页改瀑布流

前段时间看到ghost也还不错，正在研究
